    pub port: bool,
    pub svc_name: bool,
    pub protocol: bool,
    pub severity: bool,
    pub plugin_id: bool,
    pub plugin_name: bool,
    pub plugin_family: bool,

    pub agent: bool,
    pub always_run: bool,
    pub description: bool,
    pub fname: bool,
    pub plugin_modification_date: bool,
    pub plugin_publication_date: bool,
    pub risk_factor: bool,
    pub script_version: bool,
    pub solution: bool,
    pub synopsis: bool,
    pub thorough_tests: bool,
    pub plugin_output: bool,
    pub see_also: bool,
    pub bid: bool,
    pub cve: bool,
    pub xref: bool,
    pub patch_publication_date: bool,
    pub vuln_publication_date: bool,
    pub exploitability_ease: bool,
    pub exploit_available: bool,
    pub exploit_framework_canvas: bool,
    pub exploit_framework_metasploit: bool,
    pub exploit_framework_core: bool,
    pub metasploit_name: bool,
    pub canvas_package: bool,
    pub cvss_vector: bool,
    pub cvss_base_score: bool,
    pub cvss_temporal_score: bool,
    pub change: bool,
    pub plugin_type: bool,
    pub plugin_version: bool,
    pub cm_complianceinfo: bool,
    pub cm_complianceresult: bool,
    pub cm_complianceactualvalue: bool,
    pub cm_compliancecheck_id: bool,
